[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
cd app & yarn install
'''

[[plugins]]
repo = '/usr/local/opt/fzf' # fzfコマンドラインツールののフルパス
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'skanehira/translate.vim'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace' # 空白削除
[[plugins]]
repo = 'flazz/vim-colorschemes'
[[plugins]]
repo = 'jamespwilliams/bat.vim'
[[plugins]]
repo = 'jparise/vim-graphql'
#[[plugins]]
#repo = 'mhinz/vim-startify'
[[plugins]]
repo = 'Rigellute/rigel'
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'mxw/vim-jsx'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tpope/vim-repeat'


#####################
# For Vim-lsp
#####################
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'


[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'tpope/vim-endwise'

#####################
# For Go
#####################
[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'buoto/gotests-vim'

[[plugins]]
repo = 'sebdah/vim-delve'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# For test
[[plugins]]
repo = 'vim-test/vim-test'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'rhysd/vim-go-impl'

[[plugins]]
repo = '110y/vim-go-expr-completion'

##[[plugins]]
##repo = 'fatih/vim-go'

[[plugins]]
repo = 'lighttiger2505/sqls.vim'
