[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
deno task prepare
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['typescript']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['uml', 'plantuml']

[[plugins]]
repo = 'kamykn/spelunker.vim'
on_ft = ['typescript', 'vue', 'go']

#####################
# For Go
#####################
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = ['go']

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = ['go']

[[plugins]]
repo = 'rhysd/vim-go-impl'
on_ft = ['go']

[[plugins]]
repo = '110y/vim-go-expr-completion'
on_ft = ['go']

[[plugins]]
repo = 'fatih/vim-go'
on_cmd = ['IMP']

