[[plugins]]
repo = '/usr/local/opt/fzf' # fzfコマンドラインツールののフルパス
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = 'skanehira/translate.vim'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace' # 空白削除
[[plugins]]
repo = 'Rigellute/rigel'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'github/copilot.vim'


#####################
# For Vim-lsp
#####################
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# For test
[[plugins]]
repo = 'vim-test/vim-test'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'lighttiger2505/sqls.vim'
